version: "3.9"

services:
  client:
    build: ./
    container_name: client
    restart: always
    network_mode: host
    ports:
      - "3000:3000"
    environment:
      TZ: Asia/Singapore
    volumes:
      - ./../:/app
    command: sleep infinity
